services:
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - perfie_network
networks:
  perfie_network:
